In [1]:
import math
import torch
from diffusion_edf.dist import IgSO3Dist
from diffusion_edf.transforms import random_quaternions, quaternion_to_axis_angle, quaternion_apply, axis_angle_to_quaternion, quaternion_multiply, standardize_quaternion
import plotly.graph_objs as go

In [2]:
dist = IgSO3Dist()

In [3]:
q = dist.sample(eps = 0.05, N=1,)

In [4]:
eps = 0.1
angle = torch.rand(1)*eps*2

In [5]:
logP= -0.25 * angle.square() / eps - 1.5*math.log(4*eps*math.pi) # gaussian
log_haar = torch.log(
    4*math.pi*angle.square()
)

# log_haar = torch.log(
#     4*torch.sin(angle/2).square()#*(math.pi**2)
# ) # https://math.stackexchange.com/questions/3125811/haar-measure-from-axis-angle-representation-of-so3

ll_approx = logP+log_haar
print(ll_approx)

tensor([-4.0326])


In [6]:
logP = torch.log(dist._isotropic_gaussian_so3(angle, eps=eps))
log_haar = torch.log(dist.haar_measure(angle))
ll_exact= logP+log_haar
print(ll_exact)

tensor([-4.0077])


In [7]:
logP = dist.log_likelihood(q=q, eps=0.0499999)
print(logP)

tensor([0.5061])


In [8]:
logP = dist.log_likelihood(q=q, eps=0.0500001)
print(logP)

tensor([0.5057])


In [9]:
dist.log_likelihood(q=q, eps=0.0500001) - dist.log_likelihood(q=q, eps=0.0499999)

tensor([-0.0005])